In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import numpy as np
import pandas as pd
import pickle # saving and loading trained model
from os import path

# importing required libraries for normalizing data
from sklearn import preprocessing
from sklearn.preprocessing import (StandardScaler, OrdinalEncoder,LabelEncoder, MinMaxScaler, OneHotEncoder)
from sklearn.preprocessing import Normalizer, MaxAbsScaler , RobustScaler, PowerTransformer

# importing library for plotting
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('data/AWID-CLS-R-Trn/AWID-CLS-R-Trn/1',low_memory = False)

In [5]:
df.columns = ['frame.interface_id','frame.dlt','frame.offset_shift','frame.time_epoch','frame.time_delta','frame.time_delta_displayed','frame.time_relative','frame.len','frame.cap_len','frame.marked','frame.ignored','radiotap.version','radiotap.pad','radiotap.length','radiotap.present.tsft','radiotap.present.flags',
             'radiotap.present.rate','radiotap.present.channel','radiotap.present.fhss','radiotap.present.dbm_antsignal','radiotap.present.dbm_antnoise','radiotap.present.lock_quality','radiotap.present.tx_attenuation','radiotap.present.db_tx_attenuation','radiotap.present.dbm_tx_power','radiotap.present.antenna',
              'radiotap.present.db_antsignal','radiotap.present.db_antnoise','radiotap.present.rxflags','radiotap.present.xchannel','radiotap.present.mcs','radiotap.present.ampdu','radiotap.present.vht','radiotap.present.reserved','radiotap.present.rtap_ns','radiotap.present.vendor_ns','radiotap.present.ext','radiotap.mactime',
              'radiotap.flags.cfp','radiotap.flags.preamble','radiotap.flags.wep','radiotap.flags.frag','radiotap.flags.fcs','radiotap.flags.datapad','radiotap.flags.badfcs','radiotap.flags.shortgi','radiotap.datarate','radiotap.channel.freq','radiotap.channel.type.turbo','radiotap.channel.type.ofdm','radiotap.channel.type.2ghz',
              'radiotap.channel.type.5ghz','radiotap.channel.type.passive','radiotap.channel.type.dynamic','radiotap.channel.type.gfsk','radiotap.channel.type.gsm','radiotap.channel.type.sturbo','radiotap.channel.type.half','radiotap.channel.type.quarter','radiotap.dbm_antsignal','radiotap.antenna','radiotap.present.db_antsignal','radiotap.rxflags.badplcp',
              'wlan.fc.type_subtype','wlan.fc.version','wlan.fc.type','wlan.fc.subtype','wlan.fc.ds','wlan.fc.frag','wlan.fc.retry','wlan.fc.pwrmgt','wlan.fc.moredata','wlan.fc.protected','wlan.fc.order','wlan.duration','wlan.ra','wlan.da','wlan.ta','wlan.sa','wlan.bssid','wlan.frag','wlan.seq','wlan.bar.type','wlan.ba.control.ackpolicy',
              'wlan.ba.control.multitid','wlan.ba.control.cbitmap','wlan.bar.compressed.tidinfo','wlan.ba.bm','wlan.fcs_good','wlan_mgt.fixed.capabilities.ess','wlan_mgt.capabilities.ibss','wlan_mgt.fixed.capabilities.cfpoll.ap','wlan_mgt.fixed.capabilities.privacy','wlan_mgt.fixed.capabilities.preamble','wlan_mgt.fixed.capabilities.pbcc',
              'wlan_mgt.fixed.capabilities.agility','wlan_mgt.fixed.capabilities.spec_man','wlan_mgt.fixed.capabilities.short_slot_time','wlan_mgt.fixed.capabilities.apsd','wlan_mgt.fixed.capabilities.radio_measurement','wlan_mgt.fixed.capabilities.dsss_ofdm','wlan_mgt.fixed.capabilities.del_blk_ack','wlan_mgt.fixed.capabilities.imm_blk_ack',
              'wlan_mgt.fixed.listen_ival','wlan_mgt.fixed.current_ap','wlan_mgt.fixed.status_code','wlan_mgt.fixed.timestamp','wlan_mgt.fixed.beacon','wlan_mgt.fixed.aid','wlan_mgt.fixed.reason_code','wlan_mgt.fixed.auth.alg','wlan_mgt.fixed.auth_seq','wlan_mgt.fixed.category_code','wlan_mgt.fixed.htact','wlan_mgt.fixed.chanwidth','wlan_mgt.fixed.fragment','wlan_mgt.fixed.sequence',
             'wlan_mgt.tagged.all','wlan_mgt.ssid','wlan_mgt.ds.current_channel','wlan_mgt.tim.dtim_count','wlan_mgt.tim.dtim_period','wlan_mgt.tim.bmapctl.multicast','wlan_mgt.tim.bmapctl.offset','wlan_mgt.country_info.environment','wlan_mgt.rsn.version','wlan_mgt.rsn.gcs.type','wlan_mgt.rsn.pcs.count','wlan_mgt.rsn.akms.count','wlan_mgt.rsn.akms.type','wlan_mgt.rsn.capabilities.preauth',
             'wlan_mgt.rsn.capabilities.no_pairwise','wlan_mgt.rsn.capabilities.ptksa_replay_counter','wlan_mgt.rsn.capabilities.gtksa_replay_counter','wlan_mgt.rsn.capabilities.mfpr','wlan_mgt.rsn.capabilities.mfpc','wlan_mgt.rsn.capabilities,peerkey','wlan_mgt.tcprep.trsmt_pow','wlan_mgt.tcprep.link_mrg','wlan.wep.iv','wlan.wep.key','wlan.wep.icv','wlan.tkip.extiv','wlan.ccmp.extiv','wlan.qos.tid','wlan.qos.priority',
             'wlan.qos.esop','wlan.qos.ack','wlan.qos.amsdupresent','wlan.qos.buf_state_indicated','wlan.qos.bit4','wlan.qos.txop_dur_req','wlan.qos.buf_state_indicated','data.len','class']

In [6]:
from sklearn.preprocessing import LabelEncoder

encoder1= LabelEncoder().fit(df['radiotap.present.reserved'])
df['radiotap.present.reserved'] = encoder1.transform(df['radiotap.present.reserved'])

encoder2= LabelEncoder().fit(df['wlan.fc.type_subtype'])
df['wlan.fc.type_subtype'] = encoder2.transform(df['wlan.fc.type_subtype'])

encoder3= LabelEncoder().fit(df['wlan.fc.ds'])
df['wlan.fc.ds'] = encoder3.transform(df['wlan.fc.ds'])

encoder4= LabelEncoder().fit(df['wlan.sa'])
df['wlan.sa'] = encoder4.transform(df['wlan.sa'])

encoder5= LabelEncoder().fit(df['wlan.ta'])
df['wlan.ta'] = encoder5.transform(df['wlan.ta'])

encoder6= LabelEncoder().fit(df['wlan.da'])
df['wlan.da'] = encoder6.transform(df['wlan.da'])

encoder7= LabelEncoder().fit(df['wlan.ra'])
df['wlan.ra'] = encoder7.transform(df['wlan.ra'])

encoder8= LabelEncoder().fit(df['wlan.bssid'])
df['wlan.bssid'] = encoder8.transform(df['wlan.bssid'])

encoder9= LabelEncoder().fit(df['wlan.wep.iv'])
df['wlan.wep.iv'] = encoder9.transform(df['wlan.wep.iv'])

encoder10= LabelEncoder().fit(df['wlan.wep.icv'])
df['wlan.wep.icv'] = encoder10.transform(df['wlan.wep.icv'])

encoder11= LabelEncoder().fit(df['wlan.qos.ack'])
df['wlan.qos.ack'] = encoder11.transform(df['wlan.qos.ack'])

pre_num_cols = len(df.columns)

In [7]:
df.replace('?', np.nan, inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1795574 entries, 0 to 1795573
Columns: 155 entries, frame.interface_id to class
dtypes: float64(8), int64(50), object(97)
memory usage: 2.1+ GB

In [9]:
df.head()

,frame.interface_id,frame.dlt,frame.offset_shift,frame.time_epoch,frame.time_delta,frame.time_delta_displayed,frame.time_relative,frame.len,frame.cap_len,frame.marked,...,wlan.qos.priority,wlan.qos.esop,wlan.qos.ack,wlan.qos.amsdupresent,wlan.qos.buf_state_indicated,wlan.qos.bit4,wlan.qos.txop_dur_req,wlan.qos.buf_state_indicated,data.len,class
0,0,NaN,0.0,1.393661e+09,0.024271,0.024271,0.024271,185,185,0,...,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,normal
1,0,NaN,0.0,1.393661e+09,0.001631,0.001631,0.025902,185,185,0,...,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,normal
2,0,NaN,0.0,1.393661e+09,0.055325,0.055325,0.081227,159,159,0,...,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,normal
3,0,NaN,0.0,1.393661e+09,0.000415,0.000415,0.081642,54,54,0,...,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,normal
4,0,NaN,0.0,1.393661e+09,0.000005,0.000005,0.081647,40,40,0,...,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,normal

In [10]:
df.dropna(axis='columns', thresh=len(df.index)*0.20, inplace=True)

In [11]:
df1 = df.loc[df['class'] == 'normal']
df2 = df1.sample(frac=0.05, replace=False,random_state=None, axis=0)
df3 = df.loc[df['class'] != 'normal']
df4 = pd.concat([df2, df3])

In [12]:
X = df4.loc[:,:'data.len']

from sklearn import preprocessing

X.replace(np.nan,'0', inplace=True)
X = pd.DataFrame(X,dtype=np.float)

min_max_scaler = preprocessing.MinMaxScaler()
X_train = min_max_scaler.fit_transform(X)

In [13]:
y_train = df4['class']
dummies = pd.get_dummies(df4['class'], prefix='class')
y_train = dummies

In [14]:
total_count = len(df4)
normal_count = len(df4[df4['class'] == 'normal'])
flooding_count = len(df4[df4['class'] == 'flooding'])
injection_count = len(df4[df4['class'] == 'injection'])
impersonation_count = len(df4[df4['class'] == 'impersonation'])
print(f'Total number of samples：{total_count}')
print(f'normal：{normal_count}')
print(f'flooding：{flooding_count}')
print(f'injection：{injection_count}')
print(f'impersonation：{impersonation_count}')

Total number of samples：244044
normal：81659
flooding：48484
injection：65379
impersonation：48522

In [15]:
df = pd.read_csv('data/AWID-CLS-R-Tst/AWID-CLS-R-Tst/1',low_memory = False)
df.columns = ['frame.interface_id','frame.dlt','frame.offset_shift','frame.time_epoch','frame.time_delta','frame.time_delta_displayed','frame.time_relative','frame.len','frame.cap_len','frame.marked','frame.ignored','radiotap.version','radiotap.pad','radiotap.length','radiotap.present.tsft','radiotap.present.flags',
             'radiotap.present.rate','radiotap.present.channel','radiotap.present.fhss','radiotap.present.dbm_antsignal','radiotap.present.dbm_antnoise','radiotap.present.lock_quality','radiotap.present.tx_attenuation','radiotap.present.db_tx_attenuation','radiotap.present.dbm_tx_power','radiotap.present.antenna',
              'radiotap.present.db_antsignal','radiotap.present.db_antnoise','radiotap.present.rxflags','radiotap.present.xchannel','radiotap.present.mcs','radiotap.present.ampdu','radiotap.present.vht','radiotap.present.reserved','radiotap.present.rtap_ns','radiotap.present.vendor_ns','radiotap.present.ext','radiotap.mactime',
              'radiotap.flags.cfp','radiotap.flags.preamble','radiotap.flags.wep','radiotap.flags.frag','radiotap.flags.fcs','radiotap.flags.datapad','radiotap.flags.badfcs','radiotap.flags.shortgi','radiotap.datarate','radiotap.channel.freq','radiotap.channel.type.turbo','radiotap.channel.type.ofdm','radiotap.channel.type.2ghz',
              'radiotap.channel.type.5ghz','radiotap.channel.type.passive','radiotap.channel.type.dynamic','radiotap.channel.type.gfsk','radiotap.channel.type.gsm','radiotap.channel.type.sturbo','radiotap.channel.type.half','radiotap.channel.type.quarter','radiotap.dbm_antsignal','radiotap.antenna','radiotap.present.db_antsignal','radiotap.rxflags.badplcp',
              'wlan.fc.type_subtype','wlan.fc.version','wlan.fc.type','wlan.fc.subtype','wlan.fc.ds','wlan.fc.frag','wlan.fc.retry','wlan.fc.pwrmgt','wlan.fc.moredata','wlan.fc.protected','wlan.fc.order','wlan.duration','wlan.ra','wlan.da','wlan.ta','wlan.sa','wlan.bssid','wlan.frag','wlan.seq','wlan.bar.type','wlan.ba.control.ackpolicy',
              'wlan.ba.control.multitid','wlan.ba.control.cbitmap','wlan.bar.compressed.tidinfo','wlan.ba.bm','wlan.fcs_good','wlan_mgt.fixed.capabilities.ess','wlan_mgt.capabilities.ibss','wlan_mgt.fixed.capabilities.cfpoll.ap','wlan_mgt.fixed.capabilities.privacy','wlan_mgt.fixed.capabilities.preamble','wlan_mgt.fixed.capabilities.pbcc',
              'wlan_mgt.fixed.capabilities.agility','wlan_mgt.fixed.capabilities.spec_man','wlan_mgt.fixed.capabilities.short_slot_time','wlan_mgt.fixed.capabilities.apsd','wlan_mgt.fixed.capabilities.radio_measurement','wlan_mgt.fixed.capabilities.dsss_ofdm','wlan_mgt.fixed.capabilities.del_blk_ack','wlan_mgt.fixed.capabilities.imm_blk_ack',
              'wlan_mgt.fixed.listen_ival','wlan_mgt.fixed.current_ap','wlan_mgt.fixed.status_code','wlan_mgt.fixed.timestamp','wlan_mgt.fixed.beacon','wlan_mgt.fixed.aid','wlan_mgt.fixed.reason_code','wlan_mgt.fixed.auth.alg','wlan_mgt.fixed.auth_seq','wlan_mgt.fixed.category_code','wlan_mgt.fixed.htact','wlan_mgt.fixed.chanwidth','wlan_mgt.fixed.fragment','wlan_mgt.fixed.sequence',
             'wlan_mgt.tagged.all','wlan_mgt.ssid','wlan_mgt.ds.current_channel','wlan_mgt.tim.dtim_count','wlan_mgt.tim.dtim_period','wlan_mgt.tim.bmapctl.multicast','wlan_mgt.tim.bmapctl.offset','wlan_mgt.country_info.environment','wlan_mgt.rsn.version','wlan_mgt.rsn.gcs.type','wlan_mgt.rsn.pcs.count','wlan_mgt.rsn.akms.count','wlan_mgt.rsn.akms.type','wlan_mgt.rsn.capabilities.preauth',
             'wlan_mgt.rsn.capabilities.no_pairwise','wlan_mgt.rsn.capabilities.ptksa_replay_counter','wlan_mgt.rsn.capabilities.gtksa_replay_counter','wlan_mgt.rsn.capabilities.mfpr','wlan_mgt.rsn.capabilities.mfpc','wlan_mgt.rsn.capabilities,peerkey','wlan_mgt.tcprep.trsmt_pow','wlan_mgt.tcprep.link_mrg','wlan.wep.iv','wlan.wep.key','wlan.wep.icv','wlan.tkip.extiv','wlan.ccmp.extiv','wlan.qos.tid','wlan.qos.priority',
             'wlan.qos.esop','wlan.qos.ack','wlan.qos.amsdupresent','wlan.qos.buf_state_indicated','wlan.qos.bit4','wlan.qos.txop_dur_req','wlan.qos.buf_state_indicated','data.len','class']
#df.replace(np.nan, 0, inplace=True)
from sklearn.preprocessing import LabelEncoder

encoder1= LabelEncoder().fit(df['radiotap.present.reserved'])
df['radiotap.present.reserved'] = encoder1.transform(df['radiotap.present.reserved'])

encoder2= LabelEncoder().fit(df['wlan.fc.type_subtype'])
df['wlan.fc.type_subtype'] = encoder2.transform(df['wlan.fc.type_subtype'])

encoder3= LabelEncoder().fit(df['wlan.fc.ds'])
df['wlan.fc.ds'] = encoder3.transform(df['wlan.fc.ds'])

encoder4= LabelEncoder().fit(df['wlan.sa'])
df['wlan.sa'] = encoder4.transform(df['wlan.sa'])

encoder5= LabelEncoder().fit(df['wlan.ta'])
df['wlan.ta'] = encoder5.transform(df['wlan.ta'])

encoder6= LabelEncoder().fit(df['wlan.da'])
df['wlan.da'] = encoder6.transform(df['wlan.da'])

encoder7= LabelEncoder().fit(df['wlan.ra'])
df['wlan.ra'] = encoder7.transform(df['wlan.ra'])

encoder8= LabelEncoder().fit(df['wlan.bssid'])
df['wlan.bssid'] = encoder8.transform(df['wlan.bssid'])

encoder9= LabelEncoder().fit(df['wlan.wep.iv'])
df['wlan.wep.iv'] = encoder9.transform(df['wlan.wep.iv'])

encoder10= LabelEncoder().fit(df['wlan.wep.icv'])
df['wlan.wep.icv'] = encoder10.transform(df['wlan.wep.icv'])

encoder11= LabelEncoder().fit(df['wlan.qos.ack'])
df['wlan.qos.ack'] = encoder11.transform(df['wlan.qos.ack'])

pre_num_cols = len(df.columns)
df.replace('?', np.nan, inplace=True)
df.dropna(axis='columns', thresh=len(df.index)*0.20, inplace=True)
#df.replace(np.nan, 0, inplace=True)

#数据均衡化
df1 = df.loc[df['class'] == 'normal']
df2 = df1.sample(frac=0.05, replace=False,random_state=None, axis=0)
df3 = df.loc[df['class'] != 'normal']
df4 = pd.concat([df2, df3])

X = df4.loc[:,:'data.len']

from sklearn import preprocessing

X.replace(np.nan,'0', inplace=True)
X = pd.DataFrame(X,dtype=np.float)

min_max_scaler = preprocessing.MinMaxScaler()
X_test = min_max_scaler.fit_transform(X)

In [16]:
y_test = df4['class']
dummies = pd.get_dummies(df4['class'], prefix='class')
y_test = dummies
#dummies.head(5)

In [19]:
y_train

         class_flooding  class_impersonation  class_injection  class_normal
1187629               0                    0                0             1
596957                0                    0                0             1
1445972               0                    0                0             1
953197                0                    0                0             1
935467                0                    0                0             1
...                 ...                  ...              ...           ...
1682465               0                    1                0             0
1682659               0                    1                0             0
1682678               0                    1                0             0
1682696               0                    1                0             0
1682709               0                    1                0             0

[244044 rows x 4 columns]

In [18]:
X_train

array([[0.        , 0.        , 0.59371672, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.40775078, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.80340858, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.89471808, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.8947466 , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.89477383, ..., 0.        , 0.        ,
        0.        ]])